package com.example.ryousuke.thirdassignment.database

import androidx.room.Database
import androidx.room.RoomDatabase

@Database(
    entities = [ToDoEntity::class],
    version = 1,
    exportSchema = false
)
abstract class ToDoDatabase: RoomDatabase() {
    //You must inherit RoomDatabase() or, you'll get type of mismatch when you use Dagger-Hilt for building RoomDatabase.

    //this is autogenerated function for using dao function, so you don't have to write codes any more.
    abstract fun getToDoDao() : ToDoDao
}